# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0001_initial'),
        ('pessoas', '0006_auto_20160625_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
                ('evento', models.CharField(choices=[('chegada', 'chegada'), ('encaminhado à sala', 'encaminhado à sala'), ('em atendimento', 'em atendimento'), ('atendimento finalizado', 'atendimento finalizado')], max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Sessoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField(default=0)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='sessoes',
            name='tratamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamento.Tratamento'),
        ),
    ]
