# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0002_tratamento_ativo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sessoes',
            new_name='Sessao',
        ),
    ]
