# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0003_auto_20160710_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='sessao',
            name='quantidade',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='Atendimento',
        ),
    ]
