# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0006_auto_20160625_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento', models.CharField(choices=[('chegada', 'chegada'), ('encaminhado à sala', 'encaminhado à sala'), ('em atendimento', 'em atendimento'), ('atendimento finalizado', 'atendimento finalizado')], max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Pessoa')),
            ],
        ),
    ]
