# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.TextField(default='.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sobrenome',
            field=models.TextField(default='.', max_length=200),
            preserve_default=False,
        ),
    ]
