# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_auto_20160619_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('1', 'Ensino Básico'), ('2', 'Ensino Fundamental'), ('3', 'Ensino Médio'), ('4', 'Ensino Técnico'), ('5', 'Curso Superior'), ('6', 'Especialização'), ('7', 'Mestrado'), ('8', 'Doutorado')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amanozas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande no Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('1', 'Solteiro'), ('2', 'Casado'), ('3', 'Separado'), ('4', 'Divorciado'), ('5', 'Viúvo')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True),
        ),
    ]
