# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_auto_20160625_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
